/**
 * READING A CONTENT SECURITY POLICY BACK
 * ======================================
 *
 * The policy is declared in `vite.config.ts` and emitted by SvelteKit. This file
 * exists to answer a different question: **is the policy that reached the
 * browser still worth having?**
 *
 * That is not the same as "is it configured". A CSP degrades quietly. Somebody
 * adds an analytics snippet, hits the console error, adds `'unsafe-inline'` to
 * `script-src` to make it go away, and the header is still there, still long,
 * still looks like a security control, and no longer stops anything. Nothing
 * fails. No test goes red. The header is the *shape* of a policy without being
 * one.
 *
 * So the audit is code, the rules are named, and an end-to-end test runs them
 * against the real header off the real server.
 *
 * WHY `Sha256Source` COMES FROM `svelte/server`
 * ---------------------------------------------
 * Svelte 5.57 exports it:
 *
 *     export type Sha256Source = `sha256-${string}`;
 *
 * It is the type of the entries in a render's `hashes.script`, which is exactly
 * what SvelteKit's hash-mode CSP puts into `script-src`. Using Svelte's own type
 * rather than a local `string` alias means `hashesIn` cannot silently start
 * returning `'unsafe-inline'` or a bare host: a template literal type only
 * accepts something that starts `sha256-`, and the compiler checks the narrowing
 * below rather than trusting the comment above it.
 */

import type { Sha256Source } from 'svelte/server';

/** A parsed policy: directive name to its source list, both lower-cased. */
export type Policy = ReadonlyMap<string, readonly string[]>;

/**
 * Split a `Content-Security-Policy` header value into directives.
 *
 * Deliberately forgiving about whitespace and empty segments, because a header
 * assembled by concatenation somewhere upstream picks up doubled semicolons and
 * a policy this function refuses to read is a policy nobody audits.
 */
export function parsePolicy(header: string): Policy {
	const directives = new Map<string, readonly string[]>();

	for (const segment of header.split(';')) {
		const parts = segment.trim().split(/\s+/).filter(Boolean);
		const name = parts.shift()?.toLowerCase();
		if (!name) continue;

		directives.set(name, parts);
	}

	return directives;
}

/**
 * The sha256 sources in a directive, typed as Svelte types them.
 *
 * Quoted in the header — `'sha256-abc…'` — and unquoted in `hashes.script`, so
 * the quotes come off before the check. The predicate is what earns the return
 * type: nothing reaches the array without the compiler agreeing it matches
 * `sha256-${string}`.
 */
export function hashesIn(policy: Policy, directive = 'script-src'): Sha256Source[] {
	return (policy.get(directive) ?? [])
		.map((source) => source.replace(/^'|'$/g, ''))
		.filter((source): source is Sha256Source => source.startsWith('sha256-'));
}

/**
 * The nonce in a directive, if it carries one.
 *
 * Unlike a hash there is at most one, and it is different on every response —
 * which is the whole point, and also why nothing may cache a page that has one.
 * Untyped by Svelte, because a nonce is generated by SvelteKit per request
 * rather than computed from a render, so there is nothing for a template literal
 * type to check beyond the prefix.
 */
export function nonceIn(policy: Policy, directive = 'script-src'): string | null {
	const source = (policy.get(directive) ?? []).find((value) => value.startsWith("'nonce-"));
	return source ? source.slice("'nonce-".length, -1) : null;
}

/**
 * What is wrong with this policy, in the words somebody would need to fix it.
 *
 * Returns problems rather than a boolean. "The CSP is bad" is not something a
 * person can act on at four in the morning; "script-src allows 'unsafe-inline',
 * which lets an injected <script> run" is.
 *
 * The rules are the ones that decide whether a policy does anything at all —
 * not a general CSP linter, which would flag things this application has
 * decided about on purpose. `style-src 'unsafe-inline'` is absent from the list
 * for that reason: it is a deliberate trade, written down in `vite.config.ts`,
 * and a check that fires on a documented decision is a check people learn to
 * skip.
 */
export function auditPolicy(policy: Policy): string[] {
	const problems: string[] = [];
	const scripts = policy.get('script-src');

	if (!policy.has('default-src')) {
		problems.push('No `default-src`, so anything without its own directive is unrestricted.');
	}

	if (!scripts) {
		problems.push(
			'No `script-src`, so scripts fall back to `default-src` by accident rather than by decision.'
		);
	} else {
		if (scripts.includes("'unsafe-inline'")) {
			problems.push("`script-src` allows 'unsafe-inline', which lets an injected <script> run.");
		}
		if (scripts.includes("'unsafe-eval'")) {
			problems.push(
				"`script-src` allows 'unsafe-eval', which lets an injected string become code."
			);
		}
		if (scripts.includes('*')) {
			problems.push('`script-src` allows any host, so a script can be loaded from anywhere.');
		}
		if (hashesIn(policy).length === 0 && !scripts.some((source) => source.startsWith("'nonce-"))) {
			problems.push(
				'`script-src` carries neither a hash nor a nonce, so SvelteKit’s own inline bootstrap cannot run — the policy is either not in hash mode or was rewritten.'
			);
		}
	}

	/*
	 * `object-src` and `base-uri` are on this list and `frame-ancestors` is not,
	 * because the first two are bypasses and the third is a different risk.
	 *
	 *   - `object-src` un-set lets `<embed>`/`<object>` load a plugin document
	 *     that runs script outside `script-src` entirely.
	 *   - `base-uri` un-set lets an injected `<base href>` repoint every relative
	 *     URL on the page, including the ones `script-src 'self'` is trusting.
	 */
	if (policy.get('object-src')?.includes("'none'") !== true) {
		problems.push(
			"`object-src` is not 'none', which leaves a plugin document as a way around `script-src`."
		);
	}

	if (!policy.has('base-uri')) {
		problems.push(
			'No `base-uri`, so an injected <base> can repoint every relative URL on the page.'
		);
	}

	if (!policy.has('connect-src')) {
		problems.push(
			'No `connect-src`, so a script that does run may send what it read to any host it likes.'
		);
	}

	return problems;
}
