/**
 * Identifiers, and where each one is allowed to come from.
 *
 * This file is short and it decides something important: the matching engine
 * cannot invent an identifier.
 *
 * The engine has to be a pure function of the command log — feed it the same
 * commands and it must produce byte-identical events, today and in four years
 * during an investigation. `crypto.randomUUID()` breaks that instantly, and it
 * breaks it silently: replay produces a book in the same *shape* with different
 * trade IDs, so every downstream check that joins on a trade ID quietly stops
 * matching and nothing throws.
 *
 * So identifiers come from exactly two places:
 *
 *   - **Outside**, on a command, generated by the gateway before the log. Order
 *     IDs and firm IDs work this way.
 *   - **Derived**, from the sequence number that produced them. Trade IDs work
 *     this way, and they are therefore reproducible from the log alone.
 *
 * Randomness lives at the edges, where it belongs, and never inside the core.
 */

/* -------------------------------------------------------------------------- */
/* Branded identifier types                                                    */
/* -------------------------------------------------------------------------- */

/*
 * Every id is a `string` at runtime. The brand exists only for the type
 * checker, and it earns its keep the first time somebody passes an account id
 * where an order id was expected — a mistake that is invisible when both are
 * `string` and that, in this system, would attribute a fill to the wrong party.
 */

export type FirmId = string & { readonly __brand: 'FirmId' };
export type AccountId = string & { readonly __brand: 'AccountId' };
export type UserId = string & { readonly __brand: 'UserId' };
export type InstrumentId = string & { readonly __brand: 'InstrumentId' };

/** The venue's identifier for a resting order. Assigned by the gateway. */
export type OrderId = string & { readonly __brand: 'OrderId' };

/**
 * The participant's own reference for an order.
 *
 * Unique per firm, and the basis of idempotency: a client that times out and
 * retries sends the same `ClientOrderId`, and the venue must recognise it as
 * the same order rather than working it twice. An algorithmic trader with a
 * flaky connection will retry, and "we filled it twice" is not an acceptable
 * answer.
 */
export type ClientOrderId = string & { readonly __brand: 'ClientOrderId' };

/** A trade. Derived from the sequence number that created it. */
export type TradeId = string & { readonly __brand: 'TradeId' };

/* -------------------------------------------------------------------------- */
/* Constructors                                                                */
/* -------------------------------------------------------------------------- */

/** The shape every generated id shares: 26 characters of Crockford Base32. */
const ID_PATTERN = /^[0-9A-HJKMNP-TV-Z]{26}$/;

/** Human-authored identifiers — instrument symbols, mostly. */
const SYMBOL_PATTERN = /^[A-Z][A-Z0-9.]{0,15}$/;

function tag<T extends string>(value: string): T {
	return value as T;
}

export const asFirmId = (value: string): FirmId => tag<FirmId>(value);
export const asAccountId = (value: string): AccountId => tag<AccountId>(value);
export const asUserId = (value: string): UserId => tag<UserId>(value);
export const asOrderId = (value: string): OrderId => tag<OrderId>(value);
export const asClientOrderId = (value: string): ClientOrderId => tag<ClientOrderId>(value);

/** Instrument ids are symbols, and symbols are shouted. `VOD.L`, `BP.L`. */
export function asInstrumentId(value: string): InstrumentId {
	if (!SYMBOL_PATTERN.test(value)) {
		throw new RangeError(`not a valid instrument symbol: ${value}`);
	}
	return tag<InstrumentId>(value);
}

export function isGeneratedId(value: string): boolean {
	return ID_PATTERN.test(value);
}

/* -------------------------------------------------------------------------- */
/* Derived identifiers                                                         */
/* -------------------------------------------------------------------------- */

/**
 * The identifier for a trade, derived from where it happened in the log.
 *
 * `T-0000000000001834-002` is the third trade produced by command 1,834. A
 * single aggressive order can sweep several price levels and produce several
 * trades from one command, which is what the suffix is for.
 *
 * Two properties fall out of this for free, and both are worth more than they
 * cost:
 *
 *   - **Reproducible.** Replay the log and every trade gets the same id it had
 *     the first time. An auditor's query written a year ago still joins.
 *   - **Self-locating.** Given a trade id you can find the command that caused
 *     it without a lookup — the sequence number is right there in the string.
 *     During an incident that is the difference between a minute and an hour.
 *
 * The sequence number is zero-padded to sixteen digits so that lexicographic
 * order matches chronological order. That is the same reason ISO 8601 dates are
 * written most-significant-first, and it means a plain `ORDER BY trade_id`
 * sorts the tape correctly with no index on anything else.
 */
export function tradeIdFor(seq: number, index: number): TradeId {
	if (!Number.isInteger(seq) || seq < 0) throw new RangeError(`bad sequence: ${seq}`);
	if (!Number.isInteger(index) || index < 0) throw new RangeError(`bad index: ${index}`);

	return tag<TradeId>(`T-${String(seq).padStart(16, '0')}-${String(index).padStart(3, '0')}`);
}

/** Recover the sequence number a trade id was minted at. */
export function seqOfTrade(id: TradeId): number {
	const [, seq] = id.split('-');
	if (seq === undefined) throw new RangeError(`not a trade id: ${id}`);
	return Number(seq);
}
