/**
 * SEED
 * ====
 *
 * A workspace, a person, a key, and six hours of telemetry with an incident in
 * it. Run with `pnpm db:seed`.
 *
 * WHY THE DATA IS SHAPED RATHER THAN RANDOM
 * -----------------------------------------
 * Uniform random data makes every screen in an observability tool look the same,
 * and every one of them look wrong: a latency chart that is flat noise, a trace
 * where every span is the same length, an alert that never fires. None of the
 * interesting behaviour — the percentile that moves, the flame graph with one
 * fat bar, the alert that pends and then fires — is reachable from random input.
 *
 * So this generates a *story*: a normal afternoon, a dependency that starts
 * timing out, twenty minutes of errors and retries, and a recovery. Every view
 * has something to show, and it is the same story every time because the
 * generator is seeded.
 *
 * WHY THIS RUNS UNDER PLAIN NODE
 * ------------------------------
 * It imports `schema.ts`, `keys.ts` and `auth.options.ts` — and deliberately not
 * `db/index.ts` or `auth.ts`, which read `$app/env/*`. Those modules are
 * generated by SvelteKit's Vite plugin and do not exist outside it, so importing
 * them here would mean booting a Vite dev server to insert some rows.
 *
 * The price is that this file constructs its own database client. The price of
 * the alternative — configuring Better Auth a second time — is a seeded account
 * that the application rejects, so the split is drawn between *environment*
 * (duplicated, three lines) and *configuration* (shared, one function).
 */

process.loadEnvFile('.env');

import { createClient } from '@libsql/client';
import { drizzle } from 'drizzle-orm/libsql';
import { eq } from 'drizzle-orm';

import * as schema from '../src/lib/server/db/schema.ts';
import * as authSchema from '../src/lib/server/db/auth.schema.ts';
import { hashKey, newKey, prefixOf } from '../src/lib/server/keys.ts';
import { createAuth } from '../src/lib/server/auth.options.ts';

const url = process.env.DATABASE_URL;
if (!url) throw new Error('DATABASE_URL is not set. Copy .env.example to .env.');

const client = createClient({ url });
const db = drizzle(client, { schema: { ...schema, ...authSchema } });

const auth = createAuth({
	db,
	baseURL: process.env.PUBLIC_ORIGIN ?? 'http://localhost:5173',
	secret: process.env.BETTER_AUTH_SECRET ?? 'seed-secret-at-least-thirty-two-chars'
});

/* ------------------------------------------------------------------ */
/* A seeded generator                                                  */
/* ------------------------------------------------------------------ */

/**
 * mulberry32.
 *
 * The seed is fixed, so the demo is identical on every machine and every run —
 * which matters more than it sounds: a screenshot in the documentation stays
 * true, and an end-to-end test can assert on a specific trace.
 */
function random(seed: number): () => number {
	let state = seed >>> 0;
	return () => {
		state = (state + 0x6d2b79f5) >>> 0;
		let t = state;
		t = Math.imul(t ^ (t >>> 15), t | 1);
		t ^= t + Math.imul(t ^ (t >>> 7), t | 61);
		return ((t ^ (t >>> 14)) >>> 0) / 4294967296;
	};
}

const rand = random(20260901);

/** A log-normal-ish latency: mostly fast, with a tail. Real latency is never symmetric. */
function latency(median: number, spread: number): number {
	return Math.max(1, Math.round(median * Math.exp((rand() - 0.5) * spread)));
}

function pick<T>(list: readonly T[]): T {
	return list[Math.floor(rand() * list.length)]!;
}

/**
 * Deterministic hex ids, so two runs of the seed produce the same trace links.
 *
 * Seeded from a counter rather than from a timestamp, and this is not a detail.
 * The first version seeded from the span's start time, which is unique *most* of
 * the time — two requests in the same four-second tick can land on the same
 * millisecond, and then their ids are identical and the insert dies on the
 * unique index. A counter cannot collide by construction.
 *
 * The lengths are OpenTelemetry's: 32 hex characters for a trace (16 bytes) and
 * 16 for a span (8 bytes). Shortening them to 8 for readability is what made the
 * collision likely enough to hit at sixteen thousand spans — 32 bits of id and
 * the birthday bound are not friends.
 */
let counter = 0;

function hex(length: number): string {
	const next = random((counter += 1) * 2654435761);
	let out = '';
	while (out.length < length) out += Math.floor(next() * 16).toString(16);
	return out.slice(0, length);
}

/* ------------------------------------------------------------------ */
/* The story                                                           */
/* ------------------------------------------------------------------ */

const SERVICES = ['gateway', 'checkout', 'payments-api', 'inventory', 'search'] as const;
const ROUTES = ['/cart', '/checkout', '/search', '/product/{id}', '/api/orders'] as const;
const REGIONS = ['eu-west-1', 'us-east-1'] as const;

const now = Date.now();
const windowStart = now - 6 * 60 * 60 * 1000;
const incidentStart = now - 40 * 60 * 1000;
const incidentEnd = now - 20 * 60 * 1000;

const TENANT_ID = 'seed-tenant';
const SLUG = 'demo';
const EMAIL = 'ada@example.com';
const PASSWORD = 'correct-horse-battery';

function inIncident(at: number): boolean {
	return at >= incidentStart && at < incidentEnd;
}

type EventRow = typeof schema.event.$inferInsert;
type SpanRow = typeof schema.span.$inferInsert;

function spanRow(
	traceId: string,
	spanId: string,
	parentId: string,
	service: string,
	name: string,
	start: number,
	duration: number,
	broken: boolean
): SpanRow {
	return {
		tenantId: TENANT_ID,
		traceId,
		spanId,
		parentId,
		name,
		service,
		timestamp: start,
		receivedAt: start + 200,
		duration,
		status: broken && service !== 'inventory' ? 'error' : 'ok',
		attributes: JSON.stringify({ 'http.route': name.split(' ')[1] ?? name })
	};
}

function eventRow(
	at: number,
	service: string,
	level: string,
	message: string,
	traceId: string,
	spanId: string
): EventRow {
	return {
		tenantId: TENANT_ID,
		timestamp: at,
		receivedAt: at + 150,
		service,
		level,
		message,
		host: `${service}-${1 + Math.floor(rand() * 3)}`,
		traceId,
		spanId,
		attributes: JSON.stringify({ region: pick(REGIONS) })
	};
}

/**
 * Six hours of traffic, one trace at a time.
 *
 * Traces are generated as trees rather than as independent spans, because the
 * viewer's whole job is to reassemble a tree — and data that was never a tree
 * would let a broken assembler pass.
 */
function generate(): { events: EventRow[]; spans: SpanRow[] } {
	const events: EventRow[] = [];
	const spans: SpanRow[] = [];

	for (let at = windowStart; at < now; at += 4_000) {
		const requests = inIncident(at) ? 5 : 3;

		for (let i = 0; i < requests; i += 1) {
			void i;
			const traceId = hex(32);
			const route = pick(ROUTES);
			const broken = inIncident(at) && rand() < 0.55;

			const start = at + Math.floor(rand() * 3_000);
			const gatewayId = hex(16);
			const checkoutId = hex(16);
			const paymentsId = hex(16);
			const inventoryId = hex(16);

			const payments = broken ? latency(2_400, 0.4) : latency(90, 0.9);
			const inventory = latency(35, 0.8);
			const checkout = payments + inventory + latency(30, 0.6);
			const gateway = checkout + latency(12, 0.5);

			const tree: SpanRow[] = [
				spanRow(traceId, gatewayId, '', 'gateway', `GET ${route}`, start, gateway, broken),
				spanRow(
					traceId,
					checkoutId,
					gatewayId,
					'checkout',
					'checkout.submit',
					start + 6,
					checkout,
					broken
				),
				spanRow(
					traceId,
					paymentsId,
					checkoutId,
					'payments-api',
					'POST /charge',
					start + 10,
					payments,
					broken
				),
				spanRow(
					traceId,
					inventoryId,
					checkoutId,
					'inventory',
					'reserve',
					start + 12,
					inventory,
					false
				)
			];

			/*
			 * One trace in fifty loses its root.
			 *
			 * Not noise for its own sake: a missing root is common in real data — the
			 * service that would have sent it was not instrumented — and it is the
			 * case that makes a naive assembler render four separate trees instead of
			 * one. Having it in the seed means the synthetic-root path is exercised
			 * every time anybody opens the demo.
			 */
			if (rand() < 0.02) tree.shift();

			spans.push(...tree);

			events.push(
				eventRow(at, 'gateway', 'info', `${route} handled in ${gateway}ms`, traceId, gatewayId)
			);

			if (broken) {
				events.push(
					eventRow(
						at + 1,
						'payments-api',
						'error',
						'upstream timeout calling acquirer: context deadline exceeded',
						traceId,
						paymentsId
					),
					eventRow(
						at + 2,
						'checkout',
						'warn',
						'retrying charge (attempt 2 of 3)',
						traceId,
						checkoutId
					)
				);
			} else if (rand() < 0.03) {
				events.push(
					eventRow(
						at + 1,
						pick(SERVICES),
						'warn',
						'slow query: 1.4s on orders_by_user',
						traceId,
						''
					)
				);
			}
		}
	}

	return { events, spans };
}

/**
 * Insert in chunks.
 *
 * SQLite has a hard limit on the number of bound parameters in one statement,
 * and a thousand rows of twelve columns is comfortably past it. The symptom of
 * getting this wrong is `too many SQL variables`, which is a much less obvious
 * message than it should be.
 */
async function insertChunked<T>(
	table: Parameters<typeof db.insert>[0],
	rows: readonly T[],
	size: number
): Promise<void> {
	for (let i = 0; i < rows.length; i += size) {
		await db
			.insert(table)
			.values(rows.slice(i, i + size) as never)
			.run();
	}
}

/**
 * Create the demo user through Better Auth rather than by inserting rows.
 *
 * Inserting directly would mean writing a password hash by hand, in whatever
 * format the library currently expects — and the moment that format changes, the
 * seed produces an account nobody can sign in to.
 */
async function ensureUser(): Promise<string> {
	const existing = await db
		.select({ id: authSchema.user.id })
		.from(authSchema.user)
		.where(eq(authSchema.user.email, EMAIL))
		.limit(1);

	if (existing[0]) return existing[0].id;

	const created = await auth.api.signUpEmail({
		body: { email: EMAIL, password: PASSWORD, name: 'Ada Lovelace' }
	});

	return created.user.id;
}

/**
 * One trace, at a known id, with its root deliberately missing.
 *
 * The random 2% above exercises the same path and cannot be *tested* — an
 * end-to-end test that opens traces until it finds an incomplete one is a flake
 * generator, and one that asserts a random draw is worse. A fixed id makes the
 * orphan case a thing a test can name.
 *
 * The id is all `f`s so that it is obviously synthetic when it turns up in a
 * demo, and so that nobody mistakes it for a real request.
 */
export const INCOMPLETE_TRACE = 'ffffffffffffffffffffffffffffffff';

function incompleteTrace(): SpanRow[] {
	const start = now - 15 * 60 * 1000;
	const missingRoot = '0000000000000001';

	// Two children whose parent was never sent. The assembler must adopt both
	// under one synthetic root and say that it did.
	return [
		spanRow(
			INCOMPLETE_TRACE,
			'0000000000000002',
			missingRoot,
			'checkout',
			'checkout.submit',
			start,
			420,
			false
		),
		spanRow(
			INCOMPLETE_TRACE,
			'0000000000000003',
			missingRoot,
			'payments-api',
			'POST /charge',
			start + 10,
			380,
			true
		)
	];
}

async function main(): Promise<void> {
	console.info('Seeding…');

	/* ---- Remove what this script owns, and nothing else ---- */

	await db.delete(schema.outbox).where(eq(schema.outbox.tenantId, TENANT_ID));
	await db.delete(schema.event).where(eq(schema.event.tenantId, TENANT_ID));
	await db.delete(schema.span).where(eq(schema.span.tenantId, TENANT_ID));
	await db.delete(schema.sample).where(eq(schema.sample.tenantId, TENANT_ID));
	await db.delete(schema.series).where(eq(schema.series.tenantId, TENANT_ID));
	await db.delete(schema.view).where(eq(schema.view.tenantId, TENANT_ID));

	for (const rule of await db
		.select()
		.from(schema.alertRule)
		.where(eq(schema.alertRule.tenantId, TENANT_ID))) {
		await db.delete(schema.alertStatus).where(eq(schema.alertStatus.ruleId, rule.id));
	}

	await db.delete(schema.alertRule).where(eq(schema.alertRule.tenantId, TENANT_ID));
	await db.delete(schema.apiKey).where(eq(schema.apiKey.tenantId, TENANT_ID));
	await db.delete(schema.membership).where(eq(schema.membership.tenantId, TENANT_ID));
	await db.delete(schema.tenant).where(eq(schema.tenant.id, TENANT_ID));

	await db.insert(schema.tenant).values({ id: TENANT_ID, name: 'Demo', slug: SLUG });

	const userId = await ensureUser();
	await db
		.insert(schema.membership)
		.values({ id: crypto.randomUUID(), tenantId: TENANT_ID, userId, role: 'owner' });

	/* ---- An ingest key, printed once ---- */

	const key = newKey();
	await db.insert(schema.apiKey).values({
		id: crypto.randomUUID(),
		tenantId: TENANT_ID,
		name: 'seed collector',
		prefix: prefixOf(key),
		hash: await hashKey(key),
		scopes: 'ingest'
	});

	/* ---- Telemetry ---- */

	const { events, spans } = generate();
	spans.push(...incompleteTrace());

	await insertChunked(schema.event, events, 400);
	await insertChunked(schema.span, spans, 300);

	/* ---- Two rules, one of which will fire ---- */

	await db.insert(schema.alertRule).values([
		{
			id: crypto.randomUUID(),
			tenantId: TENANT_ID,
			name: 'Errors in the last five minutes',
			query: 'from logs | where level == "error" | summarize n = count()',
			threshold: 20,
			clearsAt: 10,
			forMs: 60_000,
			windowMs: 300_000,
			intervalMs: 60_000,
			direction: 'above'
		},
		{
			id: crypto.randomUUID(),
			tenantId: TENANT_ID,
			name: 'Checkout p95 latency',
			query: 'from spans | where service == "checkout" | summarize p95 = percentile(duration, 95)',
			threshold: 800,
			clearsAt: 600,
			forMs: 120_000,
			windowMs: 600_000,
			intervalMs: 60_000,
			direction: 'above'
		}
	]);

	/* ---- Saved views ---- */

	await db.insert(schema.view).values([
		{
			id: crypto.randomUUID(),
			tenantId: TENANT_ID,
			name: 'Errors by service',
			query:
				'from logs | where level == "error" | summarize n = count() by service, bucket = bin(timestamp, 1m) | sort bucket asc',
			range: '-6h',
			authorId: userId
		},
		{
			id: crypto.randomUUID(),
			tenantId: TENANT_ID,
			name: 'Slowest checkout requests',
			query: 'from spans | where service == "checkout" | sort duration desc | take 50',
			range: '-6h',
			authorId: userId
		}
	]);

	console.info(`
Seeded ${events.length.toLocaleString()} log lines and ${spans.length.toLocaleString()} spans.

  workspace  /${SLUG}
  sign in    ${EMAIL} / ${PASSWORD}
  api key    ${key}

payments-api times out between ${new Date(incidentStart).toISOString()} and
${new Date(incidentEnd).toISOString()}; checkout retries, the error-rate rule
fires, and every view has something to show.
`);

	client.close();
}

await main();
